
apiVersion: v1
kind: Service
metadata:
  name: echo-grpc
spec:
  type: ClusterIP
  selector:
    app: echo-grpc
  ports:
    - name: http2-echo
      protocol: TCP
      port: 8080
  clusterIP: None
