apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-grpc
  template:
    metadata:
      labels:
        app: echo-grpc
    spec:
      containers:
        - name: echo-grpc
          image: us-central1-docker.pkg.dev/katha-dbc46/docker-image-repository-test/grpc-test-sample:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: 50m
              ephemeral-storage: 128Mi
              memory: 128Mi