
apiVersion: v1
kind: Service
metadata:
  name: math-grpc
spec:
  type: ClusterIP
  selector:
    app: math-grpc
  ports:
    - name: http2-echo
      protocol: TCP
      port: 8082
  clusterIP: None
