apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: math-grpc
  template:
    metadata:
      labels:
        app: math-grpc
    spec:
      containers:
        - name: math-grpc
          image: us-central1-docker.pkg.dev/katha-dbc46/docker-image-repository-test/math-grpc:latest
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
          resources:
            requests:
              cpu: 50m
              ephemeral-storage: 128Mi
              memory: 128Mi